// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartCheckin.proto

package com.example.smartcheckin;

/**
 * Protobuf type {@code CheckInRequest}
 */
public  final class CheckInRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CheckInRequest)
    CheckInRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckInRequest.newBuilder() to construct.
  private CheckInRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckInRequest() {
    guestName_ = "";
    guestID_ = "";
    paymentDetails_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckInRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            guestName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            guestID_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            paymentDetails_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.smartcheckin.SmartCheckinProto.internal_static_CheckInRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.smartcheckin.SmartCheckinProto.internal_static_CheckInRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.smartcheckin.CheckInRequest.class, com.example.smartcheckin.CheckInRequest.Builder.class);
  }

  public static final int GUESTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object guestName_;
  /**
   * <code>string guestName = 1;</code>
   */
  public java.lang.String getGuestName() {
    java.lang.Object ref = guestName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      guestName_ = s;
      return s;
    }
  }
  /**
   * <code>string guestName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGuestNameBytes() {
    java.lang.Object ref = guestName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      guestName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GUESTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object guestID_;
  /**
   * <code>string guestID = 2;</code>
   */
  public java.lang.String getGuestID() {
    java.lang.Object ref = guestID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      guestID_ = s;
      return s;
    }
  }
  /**
   * <code>string guestID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGuestIDBytes() {
    java.lang.Object ref = guestID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      guestID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYMENTDETAILS_FIELD_NUMBER = 3;
  private volatile java.lang.Object paymentDetails_;
  /**
   * <code>string paymentDetails = 3;</code>
   */
  public java.lang.String getPaymentDetails() {
    java.lang.Object ref = paymentDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paymentDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string paymentDetails = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPaymentDetailsBytes() {
    java.lang.Object ref = paymentDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paymentDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getGuestNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, guestName_);
    }
    if (!getGuestIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, guestID_);
    }
    if (!getPaymentDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, paymentDetails_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGuestNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, guestName_);
    }
    if (!getGuestIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, guestID_);
    }
    if (!getPaymentDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, paymentDetails_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.smartcheckin.CheckInRequest)) {
      return super.equals(obj);
    }
    com.example.smartcheckin.CheckInRequest other = (com.example.smartcheckin.CheckInRequest) obj;

    boolean result = true;
    result = result && getGuestName()
        .equals(other.getGuestName());
    result = result && getGuestID()
        .equals(other.getGuestID());
    result = result && getPaymentDetails()
        .equals(other.getPaymentDetails());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GUESTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGuestName().hashCode();
    hash = (37 * hash) + GUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getGuestID().hashCode();
    hash = (37 * hash) + PAYMENTDETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getPaymentDetails().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.smartcheckin.CheckInRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartcheckin.CheckInRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.smartcheckin.CheckInRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.smartcheckin.CheckInRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.smartcheckin.CheckInRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CheckInRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CheckInRequest)
      com.example.smartcheckin.CheckInRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.smartcheckin.SmartCheckinProto.internal_static_CheckInRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.smartcheckin.SmartCheckinProto.internal_static_CheckInRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.smartcheckin.CheckInRequest.class, com.example.smartcheckin.CheckInRequest.Builder.class);
    }

    // Construct using com.example.smartcheckin.CheckInRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      guestName_ = "";

      guestID_ = "";

      paymentDetails_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.smartcheckin.SmartCheckinProto.internal_static_CheckInRequest_descriptor;
    }

    @java.lang.Override
    public com.example.smartcheckin.CheckInRequest getDefaultInstanceForType() {
      return com.example.smartcheckin.CheckInRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.smartcheckin.CheckInRequest build() {
      com.example.smartcheckin.CheckInRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.smartcheckin.CheckInRequest buildPartial() {
      com.example.smartcheckin.CheckInRequest result = new com.example.smartcheckin.CheckInRequest(this);
      result.guestName_ = guestName_;
      result.guestID_ = guestID_;
      result.paymentDetails_ = paymentDetails_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.smartcheckin.CheckInRequest) {
        return mergeFrom((com.example.smartcheckin.CheckInRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.smartcheckin.CheckInRequest other) {
      if (other == com.example.smartcheckin.CheckInRequest.getDefaultInstance()) return this;
      if (!other.getGuestName().isEmpty()) {
        guestName_ = other.guestName_;
        onChanged();
      }
      if (!other.getGuestID().isEmpty()) {
        guestID_ = other.guestID_;
        onChanged();
      }
      if (!other.getPaymentDetails().isEmpty()) {
        paymentDetails_ = other.paymentDetails_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.smartcheckin.CheckInRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.smartcheckin.CheckInRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object guestName_ = "";
    /**
     * <code>string guestName = 1;</code>
     */
    public java.lang.String getGuestName() {
      java.lang.Object ref = guestName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guestName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string guestName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGuestNameBytes() {
      java.lang.Object ref = guestName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guestName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string guestName = 1;</code>
     */
    public Builder setGuestName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      guestName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string guestName = 1;</code>
     */
    public Builder clearGuestName() {
      
      guestName_ = getDefaultInstance().getGuestName();
      onChanged();
      return this;
    }
    /**
     * <code>string guestName = 1;</code>
     */
    public Builder setGuestNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      guestName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object guestID_ = "";
    /**
     * <code>string guestID = 2;</code>
     */
    public java.lang.String getGuestID() {
      java.lang.Object ref = guestID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guestID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string guestID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGuestIDBytes() {
      java.lang.Object ref = guestID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guestID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string guestID = 2;</code>
     */
    public Builder setGuestID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      guestID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string guestID = 2;</code>
     */
    public Builder clearGuestID() {
      
      guestID_ = getDefaultInstance().getGuestID();
      onChanged();
      return this;
    }
    /**
     * <code>string guestID = 2;</code>
     */
    public Builder setGuestIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      guestID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object paymentDetails_ = "";
    /**
     * <code>string paymentDetails = 3;</code>
     */
    public java.lang.String getPaymentDetails() {
      java.lang.Object ref = paymentDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paymentDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string paymentDetails = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPaymentDetailsBytes() {
      java.lang.Object ref = paymentDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string paymentDetails = 3;</code>
     */
    public Builder setPaymentDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paymentDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string paymentDetails = 3;</code>
     */
    public Builder clearPaymentDetails() {
      
      paymentDetails_ = getDefaultInstance().getPaymentDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string paymentDetails = 3;</code>
     */
    public Builder setPaymentDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paymentDetails_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CheckInRequest)
  }

  // @@protoc_insertion_point(class_scope:CheckInRequest)
  private static final com.example.smartcheckin.CheckInRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.smartcheckin.CheckInRequest();
  }

  public static com.example.smartcheckin.CheckInRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckInRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckInRequest>() {
    @java.lang.Override
    public CheckInRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckInRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckInRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckInRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.smartcheckin.CheckInRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

