// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartCheckin.proto

package com.example.smartcheckin;

public interface CheckInRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckInRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string guestName = 1;</code>
   */
  java.lang.String getGuestName();
  /**
   * <code>string guestName = 1;</code>
   */
  com.google.protobuf.ByteString
      getGuestNameBytes();

  /**
   * <code>string guestID = 2;</code>
   */
  java.lang.String getGuestID();
  /**
   * <code>string guestID = 2;</code>
   */
  com.google.protobuf.ByteString
      getGuestIDBytes();

  /**
   * <code>string paymentDetails = 3;</code>
   */
  java.lang.String getPaymentDetails();
  /**
   * <code>string paymentDetails = 3;</code>
   */
  com.google.protobuf.ByteString
      getPaymentDetailsBytes();
}
