// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartCheckin.proto

package com.example.smartcheckin;

public final class SmartCheckinProto {
  private SmartCheckinProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckInRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckInRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckInResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckInResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SmartCheckin.proto\"L\n\016CheckInRequest\022\021" +
      "\n\tguestName\030\001 \001(\t\022\017\n\007guestID\030\002 \001(\t\022\026\n\016pa" +
      "ymentDetails\030\003 \001(\t\"3\n\017CheckInResponse\022\017\n" +
      "\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2C\n\023Smart" +
      "CheckinService\022,\n\007checkIn\022\017.CheckInReque" +
      "st\032\020.CheckInResponseB/\n\030com.example.smar" +
      "tcheckinB\021SmartCheckinProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CheckInRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckInRequest_descriptor,
        new java.lang.String[] { "GuestName", "GuestID", "PaymentDetails", });
    internal_static_CheckInResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CheckInResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckInResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
