// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutomatedCheckout.proto

package com.example.automatedcheckout;

public final class AutomatedCheckoutProto {
  private AutomatedCheckoutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckOutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckOutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckOutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckOutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027AutomatedCheckout.proto\"%\n\017CheckOutReq" +
      "uest\022\022\n\nroomNumber\030\001 \001(\t\"4\n\020CheckOutResp" +
      "onse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2K" +
      "\n\030AutomatedCheckoutService\022/\n\010checkOut\022\020" +
      ".CheckOutRequest\032\021.CheckOutResponseB9\n\035c" +
      "om.example.automatedcheckoutB\026AutomatedC" +
      "heckoutProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CheckOutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckOutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckOutRequest_descriptor,
        new java.lang.String[] { "RoomNumber", });
    internal_static_CheckOutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CheckOutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckOutResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
