// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutomatedCheckout.proto

package com.example.automatedcheckout;

public interface CheckOutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckOutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
