// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutomatedCheckout.proto

package com.example.automatedcheckout;

public interface CheckOutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CheckOutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomNumber = 1;</code>
   */
  java.lang.String getRoomNumber();
  /**
   * <code>string roomNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();
}
